name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - acr
variables:
  - group: variables-acr-dev
  - group: secrets-acr-dev
  - name: DOCKER_BUILDKIT
    value: 1
  - name: tag
    value: '$(Build.BuildId)'
  - name: dockerRegistryServiceConnection
    value: 'aeb4ee0f-5747-4317-9cd3-0cd5150dfee4'
  - name: imageRepository
    value: 'harebrainedbackstage'
  - name: containerRegistry
    value: '$(acrName).azurecr.io'
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/packages/backend/Dockerfile'

stages:
  - stage: build_and_test
    displayName: 'Build and Test'
    jobs:
      - job: build_backstage_backend
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Bash@3
            displayName: Build sources (yarn)
            inputs:
              targetType: 'inline'
              script: |
                yarn install --frozen-lockfile
                yarn tsc
                yarn build
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              buildContext: '$(Build.SourcesDirectory)'
              repository: '$(acrName).azurecr.io'
              dockerfile: $(dockerfilePath)
              containerRegistry: $(acrConnection)
              tags: |
                $(tag)
                latest
